version: "3.3"

services:
  tg_test:
    container_name: tg_test
    build: .
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: some_password
      BOT_TOKEN: YOUR_TOKEN

  db:
    image: postgres:11.14-alpine3.15
    restart: always
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: some_password
      POSTGRES_DB: postgres

